### ISSUE TITLE
Raw HTML is being output

### ISSUE THREAD

**Issue by oliviernt** [zynxhealth/z-mon#5]
We installed the plugin on our jenkins but after creating a new tab with the project configuration, all we can see is the raw HTML from what seems to be the index.jelly file.

### Output:
    <style>
    html,body,body  div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,strong,sub,sup,var,b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,figure,footer,header,hgroup,menu,nav,section,time,mark,audio,video{margin:0;padding:0;border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent}article,aside,figure,footer,header,hgroup,nav,section{display:block}img,object,embed{max-width:100%}html{overflow-y:scroll}ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:'';content:none}a{margin:0;padding:0;font-size:100%;vertical-align:baseline;background:transparent}del{text-decoration:line-through}abbr[title],dfn[title]{border-bottom:1px dotted #000;cursor:help}table{border-collapse:collapse;border-spacing:0}th{font-weight:bold;vertical-align:bottom}td{font-weight:normal;vertical-align:top}hr{display:block;height:1px;border:0;border-top:1px solid #ccc;margin:1em 0;padding:0}input,select{vertical-align:middle}pre{white-space:pre;white-space:pre-wrap;white-space:pre-line;word-wrap:break-word}input[type="radio"]{vertical-align:text-bottom}input[type="checkbox"]{vertical-align:bottom;*vertical-align:baseline}.ie6 input{vertical-align:text-bottom}select,input,textarea{font:99% sans-serif}table{font-size:inherit;font:100%}a:hover,a:active{outline:none}small{font-size:85%}strong,th{font-weight:bold}td,td img{vertical-align:top}sub,sup{font-size:75%;line-height:0;position:relative}sup{top:-0.5em}sub{bottom:-0.25em}pre,code,kbd,samp{font-family:monospace, sans-serif}.clickable,label,input[type=button],input[type=submit],button{cursor:pointer}button,input,select,textarea{margin:0}button{width:auto;overflow:visible}.ie7 img{-ms-interpolation-mode:bicubic}.ie6 html{filter:expression(document.execCommand("BackgroundImageCache", false, true))}.clearfix:before,.clearfix:after{content:"\0020";display:block;height:0;overflow:hidden}.clearfix:after{clear:both}.clearfix{zoom:1}body{font:13px Helmet, Freesans, sans-serif}body,select,input,textarea{color:#333}a{color:#03f}a:hover{color:#69f}::-moz-selection{background:#fcd700;color:#fff;text-shadow:none}::selection{background:#fcd700;color:#fff;text-shadow:none}a:link{-webkit-tap-highlight-color:#fcd700}ins{background-color:#fcd700;color:#000;text-decoration:none}mark{background-color:#fcd700;color:#000;font-style:italic;font-weight:bold}html{overflow:hidden}body{background-color:#000;color:#424242;font-family:'Arial', 'Helvetica', sans-serif;font-size:24px;padding:8px;overflow:hidden}body #header{overflow:hidden;margin:auto;width:90%}body #header #team-name{float:left;font-weight:600;color:#757575;margin-right:28px;font-size:28.8px}body #header #build-num{display:block;text-align:center;font-size:28.8px;font-weight:600;float:left}body #header #build-num strong{color:#757575}body #header #logo{width:160px;height:80px;float:right}body #current-cycle{overflow:hidden;margin-left:auto;margin-right:auto;margin-bottom:20px;width:90%}body #other-info{overflow:hidden;margin-left:auto;margin-right:auto;margin-bottom:20px;width:90%;border-top:1px solid #424242;padding-top:12px}body #other-info .job-container{padding-left:80px}body #other-info span.loading-wheel{left:160px}body #footer{border-top:1px solid #0f0f0f;color:#141414;padding-top:8px;font-size:10.8px;font-style:italic;text-align:right;margin:auto;width:90%}body div.job-container{width:160px;float:left;margin-left:40px;margin-right:40px;position:relative}body div.job-container .job-name{color:#f5f5f5;font-size:19.2px;font-weight:600;text-align:center;display:block;margin-left:auto;margin-right:auto}body div.job-container .last-ran{font-size:13.2px;text-align:center;display:block;color:#5c5c5c;padding-bottom:8px;line-height:24px}body div.job-container .last-ran strong{color:#fff}body div.job-container .last-ran .last-run-pass{-moz-border-radius:5px;-webkit-border-radius:5px;-khtml-border-radius:5px;border-radius:5px;color:#caff2d;background-color:#486000;border:1px solid #5b7a00;font-size:14.4px;font-weight:600;padding:0 9.6px 0 9.6px;line-height:24px;display:block;width:70%;margin:auto}body div.job-container .last-ran .last-run-fail{-moz-border-radius:5px;-webkit-border-radius:5px;-khtml-border-radius:5px;border-radius:5px;color:#f07b6b;background-color:#821b0d;border:1px solid #99200f;font-size:14.4px;font-weight:600;padding:0 9.6px 0 9.6px;line-height:24px;display:block;width:70%;margin:auto}body div.job-container .last-ran .last-run-{-moz-border-radius:5px;-webkit-border-radius:5px;-khtml-border-radius:5px;border-radius:5px;color:#8f8f8f;background-color:#292929;border:1px solid #353535;font-size:14.4px;font-weight:600;padding:0 9.6px 0 9.6px;line-height:24px;display:block;width:70%;margin:auto}body div.job-container .test-count{position:relative;height:0;margin-left:160px;top:-110.0px;color:#821b0d;font-size:16.8px;text-align:left}body div.job-container .test-count strong{font-size:33.6px;font-weight:600;color:#df2f16;clear:both;display:block}body div.job-container .job-status{-moz-border-radius:50%;-webkit-border-radius:50%;-khtml-border-radius:50%;border-radius:50%;background-color:#424242;width:100px;height:100px;margin:auto;margin-top:24px;margin-bottom:24px;color:#fff}body div.job-container .job-status .pb-container{visibility:hidden}body div.job-container .job-status .time-value{font-size:14.4px;text-align:center;display:block}body div.job-container .job-status .time-value strong{font-size:38.4px;font-weight:600;text-align:center;display:block;margin-top:12px}body div.job-container .passed{border:2px solid #7da700;background:-webkit-radial-gradient(circle, #a7e000, #486000);background:-moz-radial-gradient(circle, #94c600, #486000);background:-ms-radial-gradient(circle, #94c600, #486000);-moz-box-shadow:1px 2px 5px -1px #000;-webkit-box-shadow:1px 2px 5px -1px #424242;box-shadow:1px 2px 5px -1px #424242}body div.job-container .failed{border:2px solid #c32913;background:-webkit-radial-gradient(circle, #e93d25, #821b0d);background:-moz-radial-gradient(circle, #df2f16, #821b0d);background:-ms-radial-gradient(circle, #df2f16, #821b0d);-moz-box-shadow:1px 2px 5px -1px #000;-webkit-box-shadow:1px 2px 5px -1px #424242;box-shadow:1px 2px 5px -1px #424242}body div.job-container .running{border:2px solid #333;background:-webkit-radial-gradient(circle, #4f4f4f, #0f0f0f);background:-moz-radial-gradient(circle, #424242, #0f0f0f);background:-ms-radial-gradient(circle, #424242, #0f0f0f);-moz-box-shadow:1px 2px 5px -1px #000;-webkit-box-shadow:1px 2px 5px -1px #424242;box-shadow:1px 2px 5px -1px #424242;border:1px solid #000}body div.job-container .running .pb-container{visibility:visible;-moz-border-radius:3px;-webkit-border-radius:3px;-khtml-border-radius:3px;border-radius:3px;border:1px solid #686868;width:50px;height:4.8px;margin:auto;margin-top:9.6px;position:relative;top:-130px}body div.job-container .running .pb-container .pb-value{background-color:#5c5c5c;height:4.8px}body div.job-container .running p.time-value{position:relative;top:-124px}body div.job-container div.running:before{content:"";-moz-border-radius:50%;-webkit-border-radius:50%;-khtml-border-radius:50%;border-radius:50%;position:relative;display:block;height:124px;width:124px;top:-12px;left:-12px;background-color:gray;border:1px solid #5c5c5c;z-index:-2}body div.job-container span.loading-wheel{position:absolute;width:0;height:0;left:80px;top:100px;border-left:100px solid transparent;border-top:50px solid #000;border-top:50px solid rgba(0,0,0,0.6);z-index:-1;-webkit-animation:spin 6s linear infinite;-webkit-transform-origin:0 0;-moz-animation:spin 6s linear infinite;-moz-transform-origin:0 0}body div.job-container .running-time{position:relative;top:-124px}body div.job-container .waiting{border:2px dotted #424242;background-color:#0f0f0f}body .arrow-right{float:left;margin-top:80px;width:0;height:0;border-top:16px solid transparent;border-bottom:16px solid transparent;background-color:#000;border-left:24px solid #424242}@-webkit-keyframes spin{from{-webkit-transform:rotate(0deg)}to{-webkit-transform:rotate(360deg)}}@-moz-keyframes spin{from{-moz-transform:rotate(0deg)}to{-moz-transform:rotate(360deg)}}@-ms-keyframes spin{from{-ms-transform:rotate(0deg)}to{-ms-transform:rotate(360deg)}}
    </style>
    <meta content="3" http-equiv="refresh" />
    <div id="header">
    <div id="team-name">Z-Mon Test</div>
    <div id="build-num">[build # <strong></strong>]</div>
    <div id="logo"><img src="" /></div>
    </div>
    <div id="current-cycle">
    <div class="job-container">
    <h2 class="job-name"></h2>
    <span class="loading-wheel"></span>
    <div class="job-status ">
    <p class="time-value"></p>
    <div class="pb-container">
    <div style="width: " class="pb-value"></div>
    </div>
    </div>
    <p class="last-ran">
                last ran <strong></strong> ago
                <span class="last-run-"></span></p></div><div class="arrow-right"></div><div class="job-container"><h2 class="job-name"></h2><span class="loading-wheel"></span><div class="job-status "><p class="time-value"></p><div class="pb-container"><div style="width: " class="pb-value"></div></div></div><p class="last-ran">
                last ran <strong></strong> ago
                <span class="last-run-"></span></p></div><div class="arrow-right"></div><div class="job-container"><h2 class="job-name"></h2><span class="loading-wheel"></span><div class="job-status "><p class="time-value"></p><div class="pb-container"><div style="width: " class="pb-value"></div></div></div><p class="test-count"></p><p class="last-ran">
                last ran <strong></strong> ago
                <span class="last-run-"></span></p></div></div><div id="other-info"><div class="job-container"><h2 class="job-name"></h2><span class="loading-wheel"></span><div class="job-status "><p class="time-value"></p><div class="pb-container"><div style="width: " class="pb-value"></div></div></div><p class="test-count"></p><p class="last-ran">
                last ran <strong></strong> ago
                <span class="last-run-"></span></p></div><div class="job-container"><h2 class="job-name"></h2><span class="loading-wheel"></span><div class="job-status "><p class="time-value"></p><div class="pb-container"><div style="width: " class="pb-value"></div></div></div><p class="test-count"></p><p class="last-ran">
                last ran <strong></strong> ago
                <span class="last-run-"></span></p></div></div><div id="footer">
        created by Aslan Brooke, Steve Moyer, and Alex Tatiyants - Zynx Health, 2012
    </div>

In the configuration, the following fields are set:
- Team / Project Name
- Build And Compile Job Name
- Deploy Job Name

Are more fields required? If so, what values are expected for those fields?

Thanks for your help.

**Comment by imuchnik** [comment]
This will be resolved once the latest PR is merged.
